[build]
  command = "npm run build"

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/server/:splat"
  status = 200

[build.environment]
  NODE_VERSION = "20.19.0"

[build.processing]
  skip_processing = false

[build.processing.secrets]
  enabled = true
  omit_paths = [".netlify/functions-internal/**"]
